    
      <div class="footer">
        <div class="footer-row">Font generated by <a href="http://www.flaticon.com">flaticon.com</a> under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY</a>. The authors are: <a href="http://www.typicons.com">Stephen Hutchings</a>.</div>
      </div>
    </div>
  </body>
</html>