<!DOCTYPE html>
<html>
  <head>
    <title>E-Meet: Cute Animals (EM:CA)</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="/social/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/social/magnific-popup/magnific-popup.css">
    <link rel="stylesheet" href="/social/social.css">

    <meta name="description" content="Социальная сеть для любителей ми-ми-ми-животных">
    <meta name="keywords" content="ми-ми-ми, животные, социальная сеть">

    <script src="/social/js/jquery-2.1.1.min.js"></script>
    <script src="/social/js/main.js"></script>
    <script src="/social/magnific-popup/jquery.magnific-popup.js"></script> 
  </head>
  <body>
    <!-- Navigation -->
    <ul id="main-navigation">
      <li><a href="/" class="profile current" title="Profile"></a></li>
      <li><a href="/pets" class="pets" title="My pets"></a></li>
      <li><a href="/settings" class="settings" title="Settings"></a></li>
    </ul>

    <!-- Likemeter -->
    <div id="cutemeter">
      143
    </div>

    <!-- Main block -->
    <div id="main-box">
      <div class="photo-box">
        <div class="preview-column col1">
          <img src="/social/img/cat_480x480_1.jpeg" alt="Pic">
          <img src="/social/img/cat_480x480_2.jpeg" alt="Pic">
        </div>
        <div class="preview-column col2">
          <img src="/social/img/cat_480x480_3.jpeg" alt="Pic">
          <img src="/social/img/cat_480x480_4.jpeg" alt="Pic">
        </div>
        <div class="avatar col3">
          <img src="/social/img/rabbit_480x480_1.jpg" alt="Pic">
        </div>
        <div class="preview-column col4">
          <img src="/social/img/cat_480x480_5.jpeg" alt="Pic">
          <img src="/social/img/cat_480x480_6.jpeg" alt="Pic">
        </div>
        <div class="preview-column col5">
          <img src="/social/img/cat_480x480_7.jpeg" alt="Pic">
          <img src="/social/img/cat_480x480_8.jpeg" alt="Pic">
        </div>
      </div>
      <div id="news-best-box">
        <div class="moving-button left"></div>
        <div class="news-container">
          <a class="news" href="/social/img/cat_480x480_12.jpeg">
            <img src="/social/img/cat_480x480_12.jpeg" alt="Pic">
          </a>
          <a class="news" href="/social/img/cat_480x480_11.jpeg">
            <img src="/social/img/cat_480x480_11.jpeg" alt="Pic">
          </a>
          <a class="news" href="/social/img/cat_480x480_7.jpeg">
            <img src="/social/img/cat_480x480_7.jpeg" alt="Pic">
          </a>
          <a class="news" href="/social/img/cat_480x480_8.jpeg">
            <img src="/social/img/cat_480x480_8.jpeg" alt="Pic">
          </a>
          <a class="news" href="/social/img/cat_480x480_9.jpeg">
            <img src="/social/img/cat_480x480_9.jpeg" alt="Pic">
          </a>
          <a class="news" href="/social/img/cat_480x480_15.jpeg">
            <img src="/social/img/cat_480x480_15.jpeg" alt="Pic">
          </a>
          <a class="news" href="/social/img/cat_480x480_13.jpeg">
            <img src="/social/img/cat_480x480_13.jpeg" alt="Pic">
          </a>
          <a class="news" href="/social/img/cat_480x480_4.jpeg">
            <img src="/social/img/cat_480x480_4.jpeg" alt="Pic">
          </a>
          <a class="news" href="/social/img/cat_480x480_3.jpeg">
            <img src="/social/img/cat_480x480_3.jpeg" alt="Pic">
          </a>
          <a class="news" href="/social/img/cat_480x480_14.jpeg">
            <img src="/social/img/cat_480x480_14.jpeg" alt="Pic">
          </a>
          <a class="news" href="/social/img/cat_480x480_2.jpeg">
            <img src="/social/img/cat_480x480_2.jpeg" alt="Pic">
          </a>
          <a class="news" href="/social/img/cat_480x480_16.jpeg">
            <img src="/social/img/cat_480x480_16.jpeg" alt="Pic">
          </a>
          <a class="news" href="/social/img/cat_480x480_1.jpeg">
            <img src="/social/img/cat_480x480_1.jpeg" alt="Pic">
          </a>
          <a class="news" href="/social/img/cat_480x480_6.jpeg">
            <img src="/social/img/cat_480x480_6.jpeg" alt="Pic">
          </a>
          <a class="news" href="/social/img/cat_480x480_5.jpeg">
            <img src="/social/img/cat_480x480_5.jpeg" alt="Pic">
          </a>
        </div>
        <div class="moving-button right"></div>
      </div>
      <div class="news-main-box">Rest news</div>
      <div class="footer">
        <div class="footer-row">Font generated by <a href="http://www.flaticon.com">flaticon.com</a> under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY</a>. The authors are: <a href="http://www.typicons.com">Stephen Hutchings</a>.</div>
      </div>
    </div>
  </body>
</html>